# fly.toml app configuration file generated for devia-n8n-caio on 2025-11-24T21:56:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devia-n8n-caio'
primary_region = 'gru'

[build]
  image = 'n8nio/n8n'

[env]
  N8N_CORS_ALLOWED_ORIGINS = 'https://Caiohvboas.github.io,http://localhost:8080'
  N8N_HOST = '0.0.0.0'
  TZ = 'America/Sao_Paulo'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
